name: umshare
description: 友盟分享flutter插件，支持Android和ios.
version: 0.7.0
# author:
homepage: https://github.com/1035901787/flutter-umshare

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.arno.umshare
        pluginClass: UmsharePlugin
      ios:
        pluginClass: UmsharePlugin
      ohos:
        package: com.arno.umshare
        pluginClass: UmsharePlugin
